### ISSUE TITLE
Several HTML elements created from Directus data cannot be edited with CSS

### ISSUE THREAD

**Issue by alecmakeus** [SquaredLabs/squaredlabs.uconn.edu#100]
For example, `project.large_summary` on the project page, in the modal (`ProjectView.vue`) that appears when you select a project to view. The `p` created inside the div using Vue's `v-html` directive is not targetable with CSS.

Not sure if there is a way around this.

**Comment by gluxon** [comment]
Does giving the div that has the `v-html` a className and then targeting `.class p` not work?

**Comment by alecmakeus** [comment]
It does not

**Comment by gluxon** [comment]
Hm.. not so nice, but I guess you'll have to have a second `<style>` block without the `scoped` attribute then. Make sure that `className` is reasonably unique in that case.

**Comment by gluxon** [comment]
Ah, I take that back. Vue does have a built-in solution to this with "deep selectors".

https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors
