### ISSUE TITLE
Title backgrounds/areas on Project Cards aren't detecting length properly, creates sizing & overflow issue

### ISSUE THREAD

**Issue by alecmakeus** [SquaredLabs/squaredlabs.uconn.edu#101]
Right now there's a simple check for title character length  in `ProjectCard.vue` that adds a class, but we're going to have to continually check the component's current size against the size of the title, and adjust size accordingly.

**Comment by ColinMcNeil** [comment]
I'm not sure if we can get the component size. If there's a vanillaJS way to do it, we can use [refs](https://codingexplained.com/coding/front-end/vue-js/accessing-dom-refs).
