### ISSUE TITLE
Home page project list only displays 1 project, should display 3

### ISSUE THREAD

**Issue by alecmakeus** [SquaredLabs/squaredlabs.uconn.edu#103]

**Comment by ColinMcNeil** [comment]
It only displays the projects order 1, 2, and 3. There are no projects with label 2 or 3 because I was testing. I recommend going on the CMS and checking out the "order" attribute

**Comment by ColinMcNeil** [comment]
I'm closing this because it is not a bug. I will assign 2 projects so you can see all 3.
