### ISSUE TITLE
Person cards on home page do not display stylized 'SLink' in hovered bio

### ISSUE THREAD

**Issue by alecmakeus** [SquaredLabs/squaredlabs.uconn.edu#104]
The links displayed are user-agent styled.

**Comment by ColinMcNeil** [comment]
The links are compiled from HTML entered in directus. The only way to resolve this is to write out own html parser.

**Comment by ColinMcNeil** [comment]
I'm going to try to write a way to replace any links in the bio with our Link component

**Comment by ColinMcNeil** [comment]
See #110
