### ISSUE TITLE
Project images take a very long time to load

### ISSUE THREAD

**Issue by alecmakeus** [SquaredLabs/squaredlabs.uconn.edu#107]
@robstolarz has mentioned we already have a Thumbor instance. We should use that, or look for a package that serves our needs. 

For the best user experience and interface, we should use WebP format and leverage native progressive rendering (example [here](https://jmperezperez.com/medium-image-progressive-loading-placeholder/)). Better than the current scan-line render method.

**Comment by ColinMcNeil** [comment]
What about it takes a while to load? None of the images are actually stored in the repository. Directus is hosting them and it loads right up for me. Directus also lets us load a small thumbnail version of the image. Also, the images are all loaded asynchronously by the browser.

**Comment by alecmakeus** [comment]
See:
![loading](https://user-images.githubusercontent.com/18580335/40925645-34109906-67e8-11e8-90a0-bed5c89fece9.gif)

**Comment by ColinMcNeil** [comment]
Oh, that's because you're in development mode. Does it do it for the CI hosted page?

**Comment by gluxon** [comment]
I think Alec is right. One of those images is 4 MB and that's an unnecessary size for such a small thumbnail. In my opinion, every image from dynamically generated content (i.e. from Directus) should be pulled through a thumbnailer with its appropriate scaling set.

Can we start by investigating the [thumbnailer built into Directus](https://docs.getdirectus.com/6.4.0/#Thumbnailer)? We should make sure to whitelist sizes to prevent DDoS attacks if we use it. I'll take my assignment off of this issue for now and anyone on the team can handle this. If that person deems thumbor better than the one built into Directus, talk to me again about getting a key for thumbor again.

**Comment by ColinMcNeil** [comment]
Someone with server-side access to directus will have to edit the config to whitelist thumbnails. I can very easily implement it.

**Comment by alecmakeus** [comment]
No more than 100K [really for any image except for full-page ones].

**Comment by ColinMcNeil** [comment]
Looks like most of the images using Directus's thumbnail system are under that.
![image](https://user-images.githubusercontent.com/5000430/43462719-dbda0328-94a4-11e8-8025-96c19f2ff643.png)
