### ISSUE TITLE
Eliminate bio-text reflow when a person card is hovered

### ISSUE THREAD

**Issue by alecmakeus** [SquaredLabs/squaredlabs.uconn.edu#109]
I've tried a number of things; selectively animating properties and adding delays, tricking the width to stay constant through use of `margin` `padding` and `border-box`, but it seems the only way to prevent it is to preset the bio's width in a fixed unit, which isn't quite ideal. 

Will keep trying but any advice is welcomed.

**Comment by ColinMcNeil** [comment]
Perhaps you could hide it until the hover animation is complete?

**Comment by alecmakeus** [comment]
Yeah, that's my last-ditch solution, as it would be ideal to have it be part of the animation.

**Comment by ColinMcNeil** [comment]
You could set the container to a fixed width and transform scale from 1 to 1.2.

**Comment by alecmakeus** [comment]
But the container's widths can't be fixed (they wouldn't be responsive anymore). Right now they're set to use the grid and span 2 columns, and so their size depends on viewport width.

**Comment by ColinMcNeil** [comment]
Interesting. It seems any width transition is going to cause a reflow. The only way to do it would be fixed width, transforms, or hiding it.

**Comment by alecmakeus** [comment]
Got it. Changed the markup hierarchy for the component from 
```
wrapper
--photo
--wrapper
----wrapper
------name
------title
----about
```
to
```
wrapper
--photo
--wrapper
----name
----title
--about
```
which allowed me to use the box model and `width: 100%` to keep the size at max without reflowing. Before, since the width of the name & title section grows on hover, it was bound to mimic that behavior. Now it is not.
