### ISSUE TITLE
Make people page interactable

### ISSUE THREAD

**Issue by alecmakeus** [SquaredLabs/squaredlabs.uconn.edu#113]
There are several components to this task.

1: Active Person
---
Presently there is some terrifyingly abstract and convoluted CSS that targets an `:nth-child` to appear as though it is the 'active' or 'selected' person card. 
We should implement functionality that, instead of using a fixed, abstract selector, adds a class to the proper element. Eg, begin by automatically adding class `active` to person index 0 from the `v-for="person in people`. When the user clicks the next/previous buttons, travel up/down the list by toggling active class and from current to selected (person with index +/-1, depending on whether next/previous was clicked).

2: Inactive People
---
* 2a. The people immediately before and after the currently selected person are styled to show their portrait only and live to the left and right of the active person, respectively. These should be reactive, in that the animate into place and when they move into the active slot, their spot should in turn be filled by the person preceding/following them in the list.

* 2b. A visual index of **all** present squared labs employees should be displayed below the animated carousel, with a simple iconographic indicator of the current position in the list on top of that person's portrait. This icon traverses the list as the user does the carousel. The thumbnail portraits should also function as a quick-navigation feature — an alternate way for the user to traverse the list by clicking a portrait to view that person, instead of traveling sequentially through the carousel.

---

What I need assistance with:
- Assigning and retrieving index of current person from programmatically rendered component list
- Adding class to relevant 'item with index' via buttons
- Mirroring the active person in the visual index
- Making the visual index update the carousel

**Comment by ColinMcNeil** [comment]
> Assigning and retrieving index of current person from programmatically rendered component list

I can set up the store to do this for you today.
> Adding class to relevant 'item with index' via buttons

Not 100% sure what you mean. We can bind classes to vue variables and then use a directive method such as `v-on:click="select(person.order)"`
> Mirroring the active person in the visual index

Already did this for projects. I used the store.
```javascript
const createStore = () => {
  return new Vuex.Store({
    state: {
      theme: "white",
      selectedProject: 0
    },
    mutations: {
      setBlue(state) {
        state.theme = "blue"
      },
      setWhite(state) {
        state.theme = "white"
      },
      // Do this for people as well?
      selectProject(state, projectToSelect) {
        state.selectedProject = projectToSelect
      },
      unSelectProject(state) {
        state.selectedProject = 0
      }
    }
  })
}
```
and to access it
```javascript
computed: {
    selectedProject: function() {
      let selectedProjID = this.$store.state.selectedProject
      if (selectedProjID === 0) {
        return {}
      }
      for (let project of this.projects) {
        if (project.id === selectedProjID) return project
      }
      throw new Error("No project by id " + selectedProjID)
    }
  },
  methods: {
    setHoveredProject(project) {
      this.hoverData = {
        name: project.name,
        client: project.client,
        timespan: project.timespan,
        people: project.people
      }
    }
  }
```
finally, ProjectCard modifies it
```javascript
methods: {
    expand() {
      this.$store.commit("selectProject", this.project.id)
    }
  }
```
