### ISSUE TITLE
People card titles need to be shorter or preview section needs to respond to longer title lengths

### ISSUE THREAD

**Issue by alecmakeus** [SquaredLabs/squaredlabs.uconn.edu#114]
Similar to #101, we need some consistent way of determining word length (in px) and adjusting height accordingly.

**Comment by ColinMcNeil** [comment]
![image](https://user-images.githubusercontent.com/5000430/40976873-5d52a40c-689d-11e8-8ae4-eae419dcb0a0.png)
I think this is not intentional

**Comment by ColinMcNeil** [comment]
Or did you change the spec?

**Comment by alecmakeus** [comment]
There are no designs for + size viewports in the spec so we can play it by ear. I agree it needed to be fixed; this is what it [should] looks like now: 
<img width="1552" alt="screen shot 2018-06-05 at 1 39 13 pm" src="https://user-images.githubusercontent.com/18580335/40992833-dd09b474-68c5-11e8-81ac-ed275613d487.png">

**Comment by alecmakeus** [comment]
Oh are you referring to the way the first row of people look?

I thought you were referring to #98.

The first row is on its way to being in line with 
<img width="1267" alt="screen shot 2018-06-05 at 1 47 17 pm" src="https://user-images.githubusercontent.com/18580335/40993227-00121cd0-68c7-11e8-972d-8f981d191042.png">
spec, see zeplin.

**Comment by ColinMcNeil** [comment]
Oh, so I guess we never implemented that design

**Comment by alecmakeus** [comment]
Related: we're not even pulling this info into cards at the moment.

**Comment by alecmakeus** [comment]
No longer an issue, since we don't show job titles on small cards.
