### ISSUE TITLE
Project info is not populating with data

### ISSUE THREAD

**Issue by alecmakeus** [SquaredLabs/squaredlabs.uconn.edu#147]
Neither on the home page nor project page

**Comment by ColinMcNeil** [comment]
In your nitpicks branch, you changed `:rawhtml` to `rawhtml`.

https://github.com/SquaredLabs/squaredlabs.uconn.edu/blob/develop/src/pages/home.vue#L88

**Comment by ColinMcNeil** [comment]
Seems to be working for me. Everything is set to lorem ipsum for now.
