### ISSUE TITLE
Route to projects instead of appending an anonymous child element

### ISSUE THREAD

**Issue by alecmakeus** [SquaredLabs/squaredlabs.uconn.edu#189]
This will improve navigation patterns (allows use of the browser back button) and allow us to link directly to projects.

**Comment by ColinMcNeil** [comment]
Could you be a tad more specific? What is this referring to?

**Comment by alecmakeus** [comment]
When a user clicks on a project to view it, they should be taken to `squaredlabs.uconn.edu/projects/selectedProject` (or `squaredlabs.uconn.edu/home/selectedProject`, if they were on the home page).
