### ISSUE TITLE
Website needs favicon

### ISSUE THREAD

**Issue by Nexuist** [SquaredLabs/squaredlabs.uconn.edu#19]

**Comment by alecmakeus** [comment]
Should be a viable option in Lingo — I would say go with `square.svg`. https://www.lingoapp.com/a/1D7A29FC-0D70-4973-BB08-A591CD9AAABC/Y5D_MG6zB9P3YaPIrE4tqJm-0BzD0k9fSxewwKnj8Lo

**Comment by Nexuist** [comment]
After talking to Brandon I was recommended to use the devServer.proxy option: https://webpack.js.org/configuration/dev-server/#devserver-proxy

Should probably rewrite server.js to pull out the webpack stuff while I'm at it.
