### ISSUE TITLE
Person title font doesn't appear to render

### ISSUE THREAD

**Issue by Nexuist** [SquaredLabs/squaredlabs.uconn.edu#195]
![image](https://user-images.githubusercontent.com/1498061/45167962-3b398100-b1c8-11e8-982c-2502795f6048.png)

The position/title under Colin/anyone's name is set to `font-family: Space Mono` but it doesn't appear to be rendering as such.

**Comment by mcab** [comment]
The [connect page](https://squaredlabs.uconn.edu/connect/) suffers the same issue.

Poking around to see the requests seems that the asset is requested, but not loaded.

Could use the CDN instead to display the font.
