### ISSUE TITLE
Mail card isn't interactive

### ISSUE THREAD

**Issue by Nexuist** [SquaredLabs/squaredlabs.uconn.edu#20]
On the [current site](https://squaredlabs.uconn.edu/) the mail card in the contact section will reveal an email address when hovered. On the new site it doesn't do this.

**Comment by alecmakeus** [comment]
Each of those cards has specific hover states, which reveal content and art.
[SVG Components.zip](https://github.com/SquaredLabs/squaredlabs.uconn.edu/files/1661107/SVG.Components.zip)
