### ISSUE TITLE
/connect page buttons not working.

### ISSUE THREAD

**Issue by sarahkittyy** [SquaredLabs/squaredlabs.uconn.edu#205]
![image](https://user-images.githubusercontent.com/31551546/67584986-b8052280-f71c-11e9-99f5-b274f8a09975.png)

Neither of these buttons work / redirect anywhere. Are they meant to be buttons?

**Comment by ColinMcNeil** [comment]
They're supposed to go somewhere. Where they go, nobody knows. I'm just going to remove them.
