### ISSUE TITLE
Blank space in the jumbotron component of the home page

### ISSUE THREAD

**Issue by Nexuist** [SquaredLabs/squaredlabs.uconn.edu#21]
Due to a redesign of the navigation bar, we are left with a ton of empty space between the navbar and the projects section on the home page. Last semester we talked about making this some kind of cool interactive animation - I was hoping we could use this issue to solidify our final choice.

@alecmakeus, do you have a concrete idea on what we could use this space for? If so, could you put it down here and mock it up on Zeplin? Thanks!

**Comment by alecmakeus** [comment]
Definitely, thank you for reminding me. I'll get on it, expect something in Zeplin as well as an interaction prototype within a week.
