### ISSUE TITLE
Empty blog space

### ISSUE THREAD

**Issue by Nexuist** [SquaredLabs/squaredlabs.uconn.edu#22]
We're unsure of what to do for our blog section. What should it be? Do we make our own blog CMS, use a platform like Medium, redirect to our members' individual blogs or scrap the blog section entirely?

**Comment by alecmakeus** [comment]
I was actually under the impression that we were scrapping the blog space, due to lack of faith in a consistent supply of content (and therefore, generated interest). I'll double check with Dan.

**Comment by Nexuist** [comment]
After consulting Dan we will continue development pretending that there was no blog in the first place until we come to a consensus on how that should work.
