### ISSUE TITLE
Footer is not completed

### ISSUE THREAD

**Issue by Nexuist** [SquaredLabs/squaredlabs.uconn.edu#24]
I believe there was talk last semester about adding/removing some tabs from the footer because the [squared labs] icon would already be in the navbar and also because we don't have a Twitter account or a blog page. I also personally think that the © 2017 UConn still looks like a button even though it is darkened.

Do we keep those tabs or add new ones? Should the navbar contain less items?

**Comment by alecmakeus** [comment]
I think that the structure of the footer will remain as is, we will just be changing the links. Also, could we actually please normalize the styling for copyright block (eg, match it to the rest), as it actually will function as a link.
