### ISSUE TITLE
Host Nuxt App on the server

### ISSUE THREAD

**Issue by ColinMcNeil** [SquaredLabs/squaredlabs.uconn.edu#56]
Now that the site has been ported to Nuxt, it is still running using a single page app architecture. When generating for SSR, every page is put into its own html file. This architecture will require a different nginx setup.

**Comment by gluxon** [comment]
> When generating for SSR, every page is put into its own html file. This architecture will require a different nginx setup.

This should be the default setup for nginx. We should be able to get this working on CI without any changes to the server.
