### ISSUE TITLE
HTML doesn't fully render in project description

### ISSUE THREAD

**Issue by ColinMcNeil** [SquaredLabs/squaredlabs.uconn.edu#73]
In people and project descriptions, the `<p>Stuff</p>` works fine, but if there is `<p> <a href="stuff.com">stuff></a></p>`, it renders as plaintext instead of a link.

**Sub-task of #53**

**Comment by gluxon** [comment]
@ColinMcNeil In commit ef1e066, you added files to .gitignore, but they're still being tracked. Was that intentional?

Files: `src/assets/people.json` and `src/assets/projects.json`

**Comment by ColinMcNeil** [comment]
No, I got rid of them! Why are they back?

**Comment by gluxon** [comment]
`people.json` in the root of the project did get removed. Here's what I think happened with the other two files:

1. You deleted `src/assets/people.json` and `src/assets/projects.json`
2. The two files above got added to `.gitignore`
3. `git add .`
4. `git commit`

The above workflow doesn't actually remove files from source control, even though they're deleted from your local file system. It's a fairly common mistake. What's happening is that once the files were added to `.gitignore`, everything about those files are going to be untracked, including their deletion.

Try `git rm -f src/assets/people.json`. Then run `git status` to make sure file deletion is staged.
