### ISSUE TITLE
Move directus api calls to async data

### ISSUE THREAD

**Issue by ColinMcNeil** [SquaredLabs/squaredlabs.uconn.edu#78]
Nuxt has a function called async data ( https://nuxtjs.org/guide/async-data ) that allows the site to render content from directus without having to rebuild. I'm going to experiment with this.

**Comment by gluxon** [comment]
It should be safe to assume that the Directus endpoint will always be up. The additional complexity of caching to the file system isn't worth our time to code when the server our Directus instance is currently on hasn't had any downtime since it's been setup.

**Comment by gluxon** [comment]
@ColinMcNeil I recommend `isomorphic-fetch` over `axios`. You're welcome to go with your preference, but I just want you to be aware of the former.

https://www.javascriptstuff.com/ajax-libraries/

**Comment by ColinMcNeil** [comment]
Okay you've convinced me
