### ISSUE TITLE
Page looks too zoomed in on widescreen aspect ratios

### ISSUE THREAD

**Issue by ColinMcNeil** [SquaredLabs/squaredlabs.uconn.edu#98]
Setting body styles along the lines of:
```max-width: 1920px;
position: absolute;
right: 50%;
transform: translateX(50%);
width: 100%;
```
fixes this issue locally. For 4k and higher DPI screens we may need to scale it.

**Comment by ColinMcNeil** [comment]
![image](https://user-images.githubusercontent.com/5000430/40493433-bafb9796-5f40-11e8-814e-addcf615e81d.png)

**Comment by ColinMcNeil** [comment]
![image](https://user-images.githubusercontent.com/5000430/40976794-30b1ba64-689d-11e8-97e2-7505c1d6389b.png)
Still looks crazy big on 21:9

**Comment by alecmakeus** [comment]
More important than aspect ratio are viewport dimensions, can I get your:
Screen resolution
Screen DPI
Viewport size
?

**Comment by alecmakeus** [comment]
@ColinMcNeil How about now?

**Comment by ColinMcNeil** [comment]
Will check it when I have access to the screen again.
